[GLOBAL]
pants_version = "2.12.0"

backend_packages.add = [
  "pants.backend.python",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy",
]

[source]
root_patterns = ["/src/python"]

[python]
interpreter_constraints = ["==3.8.*"]

[python-bootstrap]
search_path = ["<PATH>", "<PYENV>"]

[test]
output = "all"
